# Numpy 基础

In [1]:
import numpy as np

## 1、创建 Array

In [2]:
lis = [1, 2, 3]
a = np.array(lis)

print('列表：', lis)
print('Array：',a)

列表： [1, 2, 3]
Array： [1 2 3]


In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)
print('shape：', a.shape)  # 形状

[[1 2 3]
 [4 5 6]]
shape： (2, 3)


In [9]:
# np.arrange 创建 Array
a = np.arange(0, 30, 2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [10]:
# 重塑
a = a.reshape(3, 5)
print(a)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [12]:
# 各种 array
print('ones:\n', np.ones((3, 2)))
print()
print('zeros:\n', np.zeros((3, 2)))
print()
print('eye:\n', np.eye(3))
print()
print('diag:\n', np.diag([1, 2, 3]))

ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

zeros:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

diag:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [13]:
# Array 操作
print(np.array([1, 2, 3] * 3))
print()
print(np.repeat([1, 2, 3], 3))

[1 2 3 1 2 3 1 2 3]

[1 1 1 2 2 2 3 3 3]


In [16]:
# 叠加
a1 = np.ones((3, 3))
a2 = np.arange(9).reshape(3, 3)

print('纵向叠加：\n', np.vstack((a1, a2)))
print()
print('横向叠加：\n', np.hstack((a1, a2)))

纵向叠加：
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

横向叠加：
 [[1. 1. 1. 0. 1. 2.]
 [1. 1. 1. 3. 4. 5.]
 [1. 1. 1. 6. 7. 8.]]


## 2、Array 操作

In [19]:
a1 = np.ones((3, 3))
a2 = np.arange(9).reshape(3, 3)

print('a1: ', a1)
print('a2: ', a2)

print()
print('a1 + a2:\n', a1 + a2)
print()
print('a1 - a2:\n', a1 - a2)
print()
print('a1 * a2:\n', a1 * a2)
print()
print('a2 ^ 2:\n', a2 ** 2)
print()
print('a1 . a2:\n', a1.dot(a2))

a1:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
a2:  [[0 1 2]
 [3 4 5]
 [6 7 8]]

a1 + a2:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

a1 - a2:
 [[ 1.  0. -1.]
 [-2. -3. -4.]
 [-5. -6. -7.]]

a1 * a2:
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

a2 ^ 2:
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

a1 . a2:
 [[ 9. 12. 15.]
 [ 9. 12. 15.]
 [ 9. 12. 15.]]


In [21]:
# 转置
a = np.arange(10).reshape(2, 5)
print(a)
print()

print(a.T)  # 转置

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [25]:
# 改变数据类型
a = np.arange(10).reshape(2, 5)
print(a)
print(a.dtype)
print()

a = a.astype('float')  # 改变数据类型
print(a)
print(a.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [26]:
# 各种统计
a = np.array([-4, -2, 1, 3, 5])

print('sum: ', a.sum())
print('min: ', a.min())
print('max: ', a.max())
print('mean: ', a.mean())
print('std: ', a.std())
print('argmax: ', a.argmax())
print('argmin: ', a.argmin())

sum:  3
min:  -4
max:  5
mean:  0.6
std:  3.2619012860600183
argmax:  4
argmin:  0


## 3、索引与切片

In [29]:
# 一维 array
a = np.arange(13) ** 2

print('a: ', a)
print('a[0:5]: ', a[0:5])

a:  [  0   1   4   9  16  25  36  49  64  81 100 121 144]
a[0:5]:  [ 0  1  4  9 16]


In [42]:
# 二维 array
a = np.arange(36).reshape((6, 6))

print('a:\n', a)
print()
print('a[1, 1]:\n', a[1, 1])
print()
print('a[3, 2:5]:\n', a[3, 2:5])

a:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

a[1, 1]:
 7

a[3, 2:5]:
 [20 21 22]


In [43]:
# 过滤
print(a[a > 20])

# 过滤并赋值
a[a > 20] = 0
print(a)

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


In [44]:
# copy() 操作，列表‘=’号赋值是地址传递，copy()才是值传递。
a = np.arange(36).reshape((6, 6))
a2 = a
a3 = a.copy()

## 4、遍历 Array

In [50]:
a = np.random.randint(0, 10, (4, 3))
print(a)

[[1 7 2]
 [8 5 3]
 [6 0 9]
 [0 4 3]]


In [49]:
for row in a:
    print(row)

[7 6 5]
[6 6 0]
[3 9 9]
[6 8 9]


In [51]:
# enumerate() 返回索引和元素
for i, row in enumerate(a):
    print('{} 行：{}'.format(i, row))
    

0 行：[1 7 2]
1 行：[8 5 3]
2 行：[6 0 9]
3 行：[0 4 3]


In [53]:
# zip() 对两个 array 进行遍历计算
a = np.random.randint(0, 10, (4, 3))
a2 = a ** 2

for i, j in zip(a, a2):
    print('{} + {} = {}'.format(i, j, i+j))

[5 2 8] + [25  4 64] = [30  6 72]
[5 7 4] + [25 49 16] = [30 56 20]
[5 8 5] + [25 64 25] = [30 72 30]
[0 7 6] + [ 0 49 36] = [ 0 56 42]
